# Generated by Django 3.1.7 on 2021-03-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('work', models.TextField(verbose_name='Выполненные работы по мероприятию')),
                ('start_date', models.DateField(verbose_name='Дата начала мероприятия')),
                ('finish_date', models.DateField(verbose_name='Дата конца мероприятия')),
                ('responsible', models.CharField(max_length=255, verbose_name='ФИО и должность лица, подтверждающего участие')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('is_co_organizer', models.BooleanField(default=False, verbose_name='Соорганизатор')),
                ('is_assistant', models.BooleanField(default=False, verbose_name='Помощь в организации')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('work', models.TextField(verbose_name='Выполненные работы по мероприятию')),
                ('start_date', models.DateField(verbose_name='Дата начала мероприятия')),
                ('finish_date', models.DateField(verbose_name='Дата конца мероприятия')),
                ('is_systematic', models.BooleanField(verbose_name='Систематична')),
                ('type', models.CharField(blank=True, choices=[('volunteer', 'Волонтёр'), ('info_support', 'Информационное обеспечение'), ('other', 'Другое')], default='other', max_length=31, null=True, verbose_name='Тип систематической деятельности')),
            ],
        ),
    ]
