# Generated by Django 3.1.7 on 2021-03-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('media_title', models.CharField(max_length=255, verbose_name='Название источника СМИ')),
                ('edition_level_choicer', models.CharField(choices=[('university', 'университетский'), ('municipal', 'городской')], max_length=255, verbose_name='Уровень издания')),
                ('co_author_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество соавторов')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='BaseApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=255, verbose_name='ФИО и должность лица, подтверждающего участие')),
            ],
        ),
        migrations.CreateModel(
            name='BaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('work', models.TextField(verbose_name='Выполненные работы по мероприятию')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.CreateModel(
            name='InformationSupportReport',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.basereport')),
                ('start_date', models.DateField(verbose_name='Начало выполнения деятельности')),
                ('final_date', models.DateField(verbose_name='Конец выполнения деятельности')),
            ],
            bases=('main_app.basereport',),
        ),
        migrations.CreateModel(
            name='OneTimeParticipationReport',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.basereport')),
                ('date', models.DateField(verbose_name='Даты проведения')),
            ],
            bases=('main_app.basereport',),
        ),
        migrations.CreateModel(
            name='SystematicReport',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.basereport')),
                ('start_date', models.DateField(verbose_name='Начало выполнения деятельности')),
                ('final_date', models.DateField(verbose_name='Конец выполнения деятельности')),
            ],
            bases=('main_app.basereport',),
        ),
        migrations.CreateModel(
            name='VolunteerReport',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.basereport')),
                ('date', models.DateField(verbose_name='Даты проведения')),
            ],
            bases=('main_app.basereport',),
        ),
        migrations.AddField(
            model_name='articleapp',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.articlereport', verbose_name='Отчёт'),
        ),
        migrations.CreateModel(
            name='VolunteerApp',
            fields=[
                ('baseapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.baseapp')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('is_teamleader', models.BooleanField(default=False, verbose_name='Тимлидер')),
                ('is_volunteer', models.BooleanField(default=False, verbose_name='Волонтёр')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.volunteerreport', verbose_name='Отчёт')),
            ],
            bases=('main_app.baseapp',),
        ),
        migrations.CreateModel(
            name='SystematicApp',
            fields=[
                ('baseapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.baseapp')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('is_co_organizer', models.BooleanField(default=False, verbose_name='Соорганизатор')),
                ('is_assistant', models.BooleanField(default=False, verbose_name='Помощь в организации')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.systematicreport', verbose_name='Отчёт')),
            ],
            bases=('main_app.baseapp',),
        ),
        migrations.CreateModel(
            name='OneTimeParticipationApp',
            fields=[
                ('baseapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.baseapp')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('is_co_organizer', models.BooleanField(default=False, verbose_name='Соорганизатор')),
                ('is_assistant', models.BooleanField(default=False, verbose_name='Помощь в организации')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.onetimeparticipationreport', verbose_name='Отчёт')),
            ],
            bases=('main_app.baseapp',),
        ),
        migrations.CreateModel(
            name='InformationSupportApp',
            fields=[
                ('baseapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.baseapp')),
                ('scores', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.informationsupportreport', verbose_name='Отчёт')),
            ],
            bases=('main_app.baseapp',),
        ),
    ]
