# Generated by Django 3.1.7 on 2021-05-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsupportapp',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimeparticipationapp',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systematicapp',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapp',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.customuser'),
            preserve_default=False,
        ),
    ]
