# Generated by Django 3.1.7 on 2021-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210506_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlereport',
            name='central_service_id',
            field=models.IntegerField(default=1, verbose_name='Id центрального сервиса'),
            preserve_default=False,
        ),
    ]
