# Generated by Django 3.1.7 on 2021-05-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210506_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsupportapp',
            name='approvation',
        ),
        migrations.RemoveField(
            model_name='onetimeparticipationapp',
            name='approvation',
        ),
        migrations.RemoveField(
            model_name='systematicapp',
            name='approvation',
        ),
        migrations.RemoveField(
            model_name='volunteerapp',
            name='approvation',
        ),
    ]
