# Generated by Django 3.1.7 on 2021-05-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210506_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approvation',
        ),
    ]
